
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Affenpinscher";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Afghan Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Aidi";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Airedale Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Akbash";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Akita Inu";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Alano Español";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Alaskan Klee Kai";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Alaskan Malamute";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Alpine Dachsbracke";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Alpine Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "American Akita";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "American Bulldog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "American Cocker Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "American Eskimo Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "American Foxhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "American Hairless Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "American Pit Bull Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "American Staffordshire Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "American Water Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Anatolian Shepherd Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Anglo-Français de Petite Vénerie";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Appenzeller Sennenhund";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Ariege Pointer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Ariegeois";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Armant";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Armenian Gampr dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Artois Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Australian Cattle Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Australian Kelpie";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Australian Shepherd";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Australian Silky Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Australian Stumpy Tail Cattle Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Australian Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Austrian Black and Tan Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Austrian Pinscher";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Azawakh";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bakharwal Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Barbet";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Basenji";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Basque Shepherd Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Basset Artésien Normand";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Basset Bleu de Gascogne";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Basset Fauve de Bretagne";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Basset Griffon Vendéen, Grand";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Basset Griffon Vendéen, Petit";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Basset Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bavarian Mountain Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Beagle";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Beagle-Harrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bearded Collie";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Beauceron";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bedlington Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Belgian Shepherd Dog (Groenendael)";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Belgian Shepherd Dog (Laekenois)";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Belgian Shepherd Dog (Malinois)";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Belgian Shepherd (Tervuren)";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bergamasco Shepherd";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Berger Blanc Suisse";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Berger Picard";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Berner Laufhund";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bernese Mountain Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bichon Frisé";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Billy";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Black and Tan Coonhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Black and Tan Virginia Foxhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bullenbeisser";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Black Norwegian Elkhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Black Russian Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Blackmouth Cur";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bleu de Gascogne, Grand";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bleu de Gascogne, Petit";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bloodhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Blue Lacy";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Blue Paul Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bluetick Coonhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Boerboel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bohemian Shepherd";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bolognese";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Border Collie";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Border Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Borzoi";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bosnian Coarse-haired Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Boston Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bouvier des Ardennes";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bouvier des Flandres";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Boxer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Boykin Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bracco Italiano";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Braque d'Auvergne";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Braque du Bourbonnais";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Braque du Puy";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Braque Francais";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Braque Saint-Germain";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Brazilian Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Briard";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Briquet Griffon Vendéen";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Brittany";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Broholmer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bruno Jura Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bucovina Shepherd Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bull and Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bull Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bull Terrier (Miniature)";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bulldog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bullmastiff";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Bully Kutta";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Burgos Pointer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Cairn Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Canaan Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Canadian Eskimo Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Cane Corso";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Cão da Serra de Aires";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Cão de Castro Laboreiro";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Cão Fila de São Miguel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Carolina Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Carpathian Shepherd Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Catahoula Cur";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Catalan Sheepdog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Caucasian Shepherd Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Cavalier King Charles Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Central Asian Shepherd Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Cesky Fousek";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Cesky Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Chesapeake Bay Retriever";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Chien Français Blanc et Noir";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Chien Français Blanc et Orange";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Chien Français Tricolore";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Chien-gris";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Chihuahua";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Chilean Fox Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Chinese Chongqing Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Chinese Crested Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Chinese Imperial Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Chinook";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Chippiparai";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Chow Chow";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Cierny Sery";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Cimarrón Uruguayo";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Cirneco dell'Etna";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Clumber Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Collie, Rough";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Collie, Smooth";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Combai";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Cordoba Fighting Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Coton de Tulear";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Cretan Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Croatian Sheepdog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Cumberland Sheepdog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Curly Coated Retriever";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Cursinu";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Czechoslovak Wolfdog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Dachshund";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Dalmatian";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Dandie Dinmont Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Danish Swedish Farmdog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Deutsche Bracke";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Doberman Pinscher";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Dogo Argentino";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Dogo Cubano";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Dogue de Bordeaux";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Drentse Patrijshond";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Drever";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Dunker";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Dutch Shepherd Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Dutch Smoushond";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "East Siberian Laika";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "East-European Shepherd";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Elo";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "English Cocker Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "English Coonhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "English Foxhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "English Mastiff";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "English Setter";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "English Shepherd";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "English Springer Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "English Toy Terrier (Black & Tan)";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "English Water Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "English White Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Entlebucher Mountain Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Épagneul Bleu de Picardie";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Estonian Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Estrela Mountain Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Eurasier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Field Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Fila Brasileiro";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Finnish Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Finnish Lapphund";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Finnish Spitz";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Flat-Coated Retriever";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Formosan Mountain Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Fox Terrier (Smooth)";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Fox Terrier, Wire";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "French Brittany";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "French Bulldog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "French Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Galgo Español";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Gascon Saintongeois";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Georgian shepherd";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "German Longhaired Pointer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "German Pinscher";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "German Rough-haired Pointer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "German Shepherd Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "German Shorthaired Pointer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "German Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "German Spitz";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "German Wirehaired Pointer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Giant Schnauzer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Glen of Imaal Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Golden Retriever";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Gordon Setter";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Gran Mastín de Borínquen";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Grand Anglo-Français Blanc et Noir";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Grand Anglo-Français Blanc et Orange";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Grand Anglo-Français Tricolore";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Grand Griffon Vendéen";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Great Dane";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Great Pyrenees";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Greater Swiss Mountain Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Greek Harehound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Greenland Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Greyhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Griffon Bleu de Gascogne";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Griffon Bruxellois";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Griffon Fauve de Bretagne";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Griffon Nivernais";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Hamiltonstövare";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Hanover Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Hare Indian Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Harrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Havanese";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Hawaiian Poi Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Himalayan Sheepdog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Hokkaido";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Hortaya Borzaya";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Hovawart";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Huntaway";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Hygenhund";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Ibizan Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Icelandic Sheepdog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Indian pariah dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Indian Spitz";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Irish Red and White Setter";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Irish Setter";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Irish Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Irish Water Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Irish Wolfhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Istrian Coarse-haired Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Istrian Shorthaired Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Italian Greyhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Jack Russell Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Jagdterrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Jämthund";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Japanese Chin";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Japanese Spitz";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Japanese Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Kaikadi";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Kai Ken";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Kangal Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Kanni";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Karakachan Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Karelian Bear Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Karst Shepherd";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Keeshond";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Kerry Beagle";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Kerry Blue Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "King Charles Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "King Shepherd";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Kintamani";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Kishu";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Komondor";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Kooikerhondje";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Koolie";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Korean Jindo Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Kromfohrländer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Kumaon Mastiff";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Kunming Wolfdog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Kurī";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Kuvasz";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Kyi-Leo";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Labrador Husky";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Labrador Retriever";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Lagotto Romagnolo";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Lakeland Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Lancashire Heeler";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Landseer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Lapponian Herder";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Leonberger";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Lhasa Apso";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Lithuanian Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Longhaired Whippet";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Löwchen";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Magyar Agár";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Mahratta Greyhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Maltese";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Manchester Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Maremma Sheepdog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "McNab";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Mexican Hairless Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Miniature Australian Shepherd";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Miniature American Shepherd";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Miniature Fox Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Miniature Pinscher";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Miniature Schnauzer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Miniature Shar Pei";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Mioritic";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Molossus";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Montenegrin Mountain Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Moscow Watchdog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Moscow Water Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Mountain Cur";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Mucuchies";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Mudhol Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Mudi";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Münsterländer, Large";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Münsterländer, Small";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Neapolitan Mastiff";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Newfoundland";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "New Zealand Heading Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Norfolk Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Norfolk Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Norrbottenspets";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "North Country Beagle";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Northern Inuit Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Norwegian Buhund";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Norwegian Elkhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Norwegian Lundehund";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Norwich Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Nova Scotia Duck-Tolling Retriever";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Old Croatian Sighthound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Old Danish Pointer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Old English Sheepdog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Old English Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Old German Shepherd Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Old Time Farm Shepherd";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Olde English Bulldogge";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Otterhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Pachon Navarro";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Pandikona";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Paisley Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Papillon";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Parson Russell Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Patterdale Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Pekingese";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Perro de Presa Canario";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Perro de Presa Mallorquin";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Peruvian Hairless Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Phalène";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Pharaoh Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Phu Quoc ridgeback dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Picardy Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Plott Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Podenco Canario";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Pointer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Polish Greyhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Polish Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Polish Hunting Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Polish Lowland Sheepdog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Polish Tatra Sheepdog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Pomeranian";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Pont-Audemer Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Poodle";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Porcelaine";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Portuguese Podengo";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Portuguese Pointer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Portuguese Water Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Posavac Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Pražský Krysařík";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Pudelpointer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Pug";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Puli";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Pumi";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Pungsan Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Pyrenean Mastiff";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Pyrenean Shepherd";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Rafeiro do Alentejo";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Rajapalayam";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Rampur Greyhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Rastreador Brasileiro";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Ratonero Bodeguero Andaluz";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Ratonero Valenciano";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Rat Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Redbone Coonhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Rhodesian Ridgeback";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Rottweiler";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Russian Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Russian Toy";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Russian tracker";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Russo-European Laika";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Russell Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Saarlooswolfhond";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Sabueso Español";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Saint-Usuge Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Sakhalin Husky";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Saluki";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Samoyed";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Sapsali";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Šarplaninac";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Schapendoes";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Schillerstövare";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Schipperke";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Standard Schnauzer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Schweizer Laufhund";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Schweizerischer Niederlaufhund";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Scotch Collie";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Scottish Deerhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Scottish Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Sealyham Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Segugio Italiano";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Seppala Siberian Sleddog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Serbian Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Serbian Tricolour Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Shar Pei";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Shetland Sheepdog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Shiba Inu";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Shih Tzu";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Shikoku";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Shiloh Shepherd Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Siberian Husky";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Silken Windhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Sinhala Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Skye Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Sloughi";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Slovak Cuvac";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Slovakian Rough-haired Pointer";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Slovenský Kopov";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Smålandsstövare";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Small Greek Domestic Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Soft-Coated Wheaten Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "South Russian Ovcharka";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Southern Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Spanish Mastiff";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Spanish Water Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Spinone Italiano";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Sporting Lucas Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "St. Bernard";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "St. John's water dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Stabyhoun";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Staffordshire Bull Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Stephens Cur";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Styrian Coarse-haired Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Sussex Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Swedish Lapphund";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Swedish Vallhund";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Tahltan Bear Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Taigan";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Talbot";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Tamaskan Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Teddy Roosevelt Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Telomian";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Tennessee Treeing Brindle";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Tenterfield Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Thai Bangkaew Dog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Thai Ridgeback";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Tibetan Mastiff";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Tibetan Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Tibetan Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Tornjak";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Tosa";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Toy Bulldog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Toy Fox Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Toy Manchester Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Toy Trawler Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Transylvanian Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Treeing Cur";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Treeing Walker Coonhound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Trigg Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Tweed Water Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Tyrolean Hound";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Vizsla";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Volpino Italiano";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Weimaraner";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Welsh Corgi, Cardigan";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Welsh Corgi, Pembroke";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Welsh Sheepdog";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Welsh Springer Spaniel";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Welsh Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "West Highland White Terrier";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "West Siberian Laika";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Westphalian Dachsbracke";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Wetterhoun";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Whippet";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "White Shepherd";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Wirehaired Pointing Griffon";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Wirehaired Vizsla";
insert into	`pet_breed` set `pet_type_id` = "1", `v` = "Yorkshire Terrier";