
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Abyssinian";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Aegean cat";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Australian Mist";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "American Curl";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "American Bobtail";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "American Polydactyl";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "American Shorthair";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "American Wirehair";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Arabian Mau";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Asian (cat)";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Asian Semi-longhair";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Balinese";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Bambino";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Bengal";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Birman";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Bombay";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Brazilian Shorthair";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "British Shorthair";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "British Longhair";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Burmese";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Burmilla";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "California Spangled Cat";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Chantilly/Tiffany";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Chartreux";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Chausie";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Cheetoh";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Colorpoint Shorthair";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Cornish Rex";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Cymric";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Cyprus cat";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Devon Rex";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Donskoy";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Dragon Li";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Dwelf";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Egyptian Mau";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "European Shorthair";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Exotic Shorthair";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "German Rex";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Havana Brown";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Highlander";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Himalayan";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Colorpoint Persian";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Japanese Bobtail";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Javanese";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Khao Manee";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Korat";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Korn Ja";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Kurilian Bobtail";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "LaPerm";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Maine Coon";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Manx";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Mekong bobtail";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Minskin";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Munchkin";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Nebelung";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Napoleon";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Norwegian Forest Cat";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Ocicat";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Ojos Azules";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Oregon Rex";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Oriental Bicolor";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Oriental Shorthair";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Oriental Longhair";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Persian";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Peterbald";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Pixie-bob";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Ragamuffin";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Ragdoll";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Russian Blue";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Russian Black, White or Tabby";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Sam Sawet";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Savannah";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Scottish Fold";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Selkirk Rex";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Serengeti cat";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Serrade petit";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Siamese";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Siberian";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Singapura";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Snowshoe";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Sokoke";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Somali";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Sphynx";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Swedish forest cat";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Thai";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Tonkinese";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Toyger";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Turkish Angora";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Turkish Van";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "Ukrainian Levkoy";
insert into    `pet_breed` set `pet_type_id` = "2", `v` = "York Chocolate Cat";