
    <h4><i class="fa fa-ellipsis-v"></i> Tax settings</h4>
    <form form-submit hide-show-al-submit="true" submit-btn="true" submit-btn-text="Save" t="tax_settings" table="tax_settings"
          id="taxSettingsForm" action="" method="post" enctype="multipart/form-data" class="" data-abide="true">
        <div class="small-6 column">
            <fieldset class="none-bg">
                <legend>Taxable items</legend>
                <div class="small-6 column">
                    <input-text
                        title="State tax"
                        t="tax_settings" n="state_tax" v="v">
                    </input-text>
                    <input-checkbox
                        title="Boarding"
                        t="tax_settings" n="s_boarding">
                    </input-checkbox>
                    <input-checkbox
                        title="Grooms"
                        t="tax_settings" n="s_grooms">
                    </input-checkbox>
                    <input-checkbox
                        title="Baths"
                        t="tax_settings" n="s_baths">
                    </input-checkbox>
                    <input-checkbox
                        title="Medications"
                        t="tax_settings" n="s_medications">
                    </input-checkbox>
                </div>
                <div class="small-6 column">
                    <input-checkbox
                        title="Diets"
                        t="tax_settings" n="s_diets">
                    </input-checkbox>
                    <input-checkbox
                        title="Retail" disabled="disabled"
                        t="tax_settings" n="s_retail">
                    </input-checkbox>
                    <input-checkbox
                        title="Services"
                        t="tax_settings" n="s_services">
                    </input-checkbox>
                    <input-checkbox
                        title="Training"
                        t="tax_settings" n="s_training">
                    </input-checkbox>
                    <input-checkbox
                        title="Daycare/Dayboard"
                        t="tax_settings" n="s_daycare">
                    </input-checkbox>
                </div>
            </fieldset>
        </div>
        <div class="small-6 column">
            <fieldset class="none-bg">
                <legend>Optional tax</legend>
                <div class="small-12">
                    <div class="small-4 column">
                        <input-checkbox
                            title="In use"
                            t="tax_settings" n="o_tax_in_use">
                        </input-checkbox>
                    </div>
                    <div class="small-4 column">
                        <input-text
                            title="Tax name"
                            t="tax_settings" n="o_tax_name">
                        </input-text>
                    </div>
                    <div class="small-4 column">
                        <input-text
                            title="Tax amount"
                            t="tax_settings" n="o_tax_amount">
                        </input-text>
                    </div>
                </div>
                <div class="small-6 column">
                    <input-checkbox
                        title="Boarding"
                        t="tax_settings" n="o_boarding">
                    </input-checkbox>
                    <input-checkbox
                        title="Grooms"
                        t="tax_settings" n="o_grooms">
                    </input-checkbox>
                    <input-checkbox
                        title="Baths"
                        t="tax_settings" n="o_baths">
                    </input-checkbox>
                    <input-checkbox
                        title="Medications"
                        t="tax_settings" n="o_medications">
                    </input-checkbox>
                </div>
                <div class="small-6 column">
                    <input-checkbox
                        title="Diets"
                        t="tax_settings" n="o_diets">
                    </input-checkbox>
                    <input-checkbox
                        title="Retail" disabled="disabled"
                        t="tax_settings" n="o_retail">
                    </input-checkbox>
                    <input-checkbox
                        title="Services"
                        t="tax_settings" n="o_services">
                    </input-checkbox>
                    <input-checkbox
                        title="Training"
                        t="tax_settings" n="o_training">
                    </input-checkbox>
                    <input-checkbox
                        title="Daycare/Dayboard"
                        t="tax_settings" n="o_daycare">
                    </input-checkbox>
                </div>
            </fieldset>
        </div>
    </form>