
    <div class="small-8 column">
        <fieldset>
            <legend>Password management</legend>
            <form form-submit hide-show-al-content="true" submit-btn="true" t="user" table="users"
                  id="userForm" action="" method="post" enctype="multipart/form-data" data-abide="true">
                <input-select
                    title="Select employee" t="user" n="id"
                    s="$root.users" required="required">
                </input-select>
                <hr />
                <input-text
                    title="Password" t="user" n="password" id="password"
                    type="password" required="true">
                </input-text>
                <input-text
                    title="Confirm password" t="user" n="c_password" id="c_password"
                    error-text="Passwords must match" type="password"
                    required="required" equalto="password">
                </input-text>
            </form>
        </fieldset>
    </div>