<div id="pets-sticky"
     class="sticky-note bg-gr-yellow">
    <a class="close-item"
       ng-click="fadeOutElement('#pets-sticky')"></a>
    <div class="small-4 column">
        <i class="fa fa-2x fa-trash left"
           ng-show="pet.sticky.user_id"
           style="cursor: pointer; margin-right: 10px;"
           ng-click="deleteSticky('pet')"></i>
        <i class="fa fa-2x fa-save left"
           style="cursor: pointer;"
           ng-click="saveSticky('pet')"></i>
    </div>
    <div class="small-8 column"
         ng-show="pet.sticky.user_id">
        <i>by "{{users[pet.sticky.user_id].first_name}}, {{users[pet.sticky.user_id].last_name}}"</i> <br />
        <sub>Updated - {{pet.sticky.date}}</sub> <br />
        <sub>{{pet.pet_name}}, {{pet_breed[pet.pet_breed_id].v}}</sub>
    </div>
    <div class="small-8 column"
         ng-hide="pet.sticky.user_id">
        <i>by "{{identity.first_name}}, {{identity.last_name}}"</i> <br />
        <sub>Date / Time - {{getCDT()}}</sub> <br />
        <sub>{{pet.pet_name}}, {{pet_breed[pet.pet_breed_id].v}}</sub>
    </div>
    <div class="clearfix">&nbsp;</div>
    <div class="small-12">
        <input-textarea
            title="" no-error="true"
            placeholder="Enter your message ..."
            ng-model="pet.sticky.v">
        </input-textarea>
    </div>
</div>