
    <input-select
        title="Status" t="crud_mod" n="status_id"
        s="status" required="true">
    </input-select>
    <input-text
        title="Service name" t="crud_mod"
        n="v" required="required">
    </input-text>
    <input-textarea
        title="Service description" t="crud_mod"
        n="service_description">
    </input-textarea>
    <input-text
        title="Price" t="crud_mod"
        n="price" required="required">
    </input-text>
    <input-checkbox
        title="Is special ?"
        t="crud_mod" n="is_special">
    </input-checkbox>
    <input-text
        title="Limit" t="crud_mod"
        n="limit" required="required">
    </input-text>
    <input-checkbox
        title="Handle carefully price ?"
        t="crud_mod" n="is_hcp">
    </input-checkbox>
    <input-text
        title="Order" t="crud_mod" n="order">
    </input-text>
    <input-checkbox
        title="Is pickup and delivery ?"
        t="crud_mod" n="is_pickup_and_delivery">
    </input-checkbox>
    <hr />
    <input-select
        title="Daycare group" t="crud_mod" n="daycare_group_id"
        s="daycare_groups">
    </input-select>
    <hr />
    <input-text
        title="Commission percentage" t="crud_mod" n="commission_percentage">
    </input-text>
