<div class="small-7 small-offset-1" style="margin-top: 50px;">
    <img src="<?= $this->baseUrl('img/error.gif') ?>" alt="" style="height: 120px; width: auto; float: right" />
    <h1>An error occurred</h1>
    <h2><?php echo $this->message ?></h2>
    <a href="<?= $this->baseUrl('/') ?>">Click here to go to home page</a>
    <?php if (isset($this->exception)): ?>
        <h3>Exception information:</h3>
        <p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>
        <h3>Stack trace:</h3>
        <pre><?php echo $this->exception->getTraceAsString() ?></pre>
        <h3>Request Parameters:</h3>
        <pre><?php echo var_export($this->request->getParams(), true) ?></pre>
    <?php endif ?>
</div>